- name: Configuration nagios server
  hosts: server
  tasks:

    - name: Установка необходимых пакетов
      apt:
        pkg:
        - openssh-server
        - autoconf
        - gcc 
        - libc6 
        - make 
        - wget 
        - unzip 
        - apache2 
        - php 
        - libapache2-mod-php7.4 
        - libgd-dev
        - openssl 
        - libssl-dev
        update_cache: yes

    - name: Config user and group
      shell: |
        useradd nagios
        groupadd nagcmd
        usermod -a -G nagcmd nagios
        usermod -a -G nagcmd www-data
    
    - name: Send nagios files on server
      copy:
        src: '{{ item }}'
        dest: '{{ item }}'
      loop:
        - ~/nagios-4.4.6
        - ~/nagios-plugins-2.2.1

    - name: Config nagios-server
      shell: |
        cd ~/nagios-4.4.6
        ./configure --with-nagios-group=nagios --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled/
        make all
        make install
        make install-init
        make install-config
        make install-commandmode
        make install-webconf

    # Настройка контактов на сервере
    - name: Config contacts.cfg (Проверить работоспособность)
      copy:
        src: ./server_contacts.cfg
        dest: /usr/local/nagios/etc/objects/contacts.cfg
    # Вставить код для изменения файла /usr/local/nagios/etc/objects/contacts.cfg или написать свой файл и отправить на сервер
    # Верхнее поменять под себя + добавить telegram/slack/vk

    - name: Setup password for nagiosadmin
    # Реализовать этот код ---> htpasswd -c /usr/local/nagios/etc/htpasswd.users nagiosadmin(Требует ввод пароля в консоли) или сделать свой 
    # htpasswd -p {{ password }} -c /usr/local/nagios/etc/htpasswd.users nagiosadmin <-- протестировать это (вместо {{ password }} - свой пароль)
      shell: htpasswd -p {{ password }} -c /usr/local/nagios/etc/htpasswd.users nagiosadmin

    - name: Включение cgi скриптов, restart apache2
      shell: |
        a2enmod cgi
        service apache2 restart

    - name: Настройка плагинов nagios
      shell: | 
        cd ~/nagios-plugins-2.2.1
        ./configure --with-nagios-user=nagios --with-nagios-group=nagios
        make
        make install
        /usr/local/nagios/bin/nagios -v /usr/local/nagios/etc/nagios.cfg 
      # ^ проверка на ошибки ^ 


    #  Настройка сервиса Nagios для сервера
    - name: Реализовать сервис для nagios
      copy:
        src: ~/nagios_playbooks/nagios_service.service
        dest: ~/.config/systemd/root/nagios_service.service

    - name: Проверка и запуск сервиса
      shell: | 
        systemctl --user daemon-reload
        systemctl --user list-unit-files nagios_service.service
        systemctl --user enable --now nagios_service.service



    # ДОПИСАТЬ КОНФИГИ МОНИТОРИНГА СЕРВИСОВ ДЛЯ ВСЕХ ХОСТОВ + настроить их

    # Конфиги мониторинга сервисов на удалённых хостах
    - name: Создание директории для конфигов хостов
      file: 
        path: /usr/local/nagios/etc/mls # путь заменить на свой
        mode: 0775
        owner: nagios
        group: nagios
        state: directory

    - name: Создание файла для каждого хоста .cfg
      copy:
        src: ~/nagios_playbooks/mon_mls_services_for_serv.cfg
        dest: /usr/local/nagios/etc/mls/{{ item }}.cfg
        mode: 0775
        owner: nagios
        group: nagios
      loop:
      - "{{ groups['mls'] }}"

    # Возможно реализация через ml playbook
    - name: Получение имени хостов и запись их имени в файл

    - name: настройка firewall (Уточнить)
    #iptables -A INPUT -p tcp --dport 80 -j ACCEPT
    #iptables-save

    - name: Запуск Nagios
      shell: systemctl start nagios